# Generated by Django 5.0.4 on 2024-04-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('analysis', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('message_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
