# Generated by Django 5.0.4 on 2024-04-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('from_email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('body', models.TextField()),
                ('event_details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
