# Generated by Django 5.0.4 on 2024-04-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('address', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
