# Generated by Django 5.0.4 on 2024-04-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catch_date', '0003_alter_event_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(max_length=255),
        ),
    ]
